version: 2.1
executors:
  gcloud-executor:
    docker:
      - image: google/cloud-sdk

  machine-executor:
    machine: true

orbs:
  node: circleci/node@5.1
  gcp-gcr: circleci/gcp-gcr@0.15.3
  cloudrun: circleci/gcp-cloud-run@1.0.2

workflows:
  build_gcloud_deploy:
    jobs:
      - tests
      - build_push_image_gcr:
          requires:
            - tests
      - gcp_cloudrun_deploy:
          requires:
            - build_push_image_gcr

jobs:
  tests:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: yarn test:unit
          name: Run tests
      
  build_push_image_gcr:
    description: Build docker image and push to gcr registry
    executor: gcp-gcr/default
    steps:
      - checkout
      - gcp-gcr/gcr-auth
      - gcp-gcr/build-image:
          dockerfile: Dockerfile
          image: vue-application
          registry-url: "gcr.io"
          tag: $CIRCLE_SHA1

      - gcp-gcr/push-image:
          image: vue-application
          registry-url: "gcr.io"
          tag: $CIRCLE_SHA1

  gcp_cloudrun_deploy:
    description: Deploy using cloud run
    docker:
      - image: cimg/base:stable
    steps:
      - cloudrun/init
      - cloudrun/deploy:
          cluster: 'autopilot-cluster-1'
          cluster-location: us-central1
          platform: 'gke'
          image: 'gcr.io/${GOOGLE_PROJECT_ID}/vue-application:$CIRCLE_SHA1'
          service-name: 'feedback-ui-service'