version: 2.1
executors:
  gcloud-executor:
    docker:
      - image: google/cloud-sdk

  machine-executor:
    machine: true

orbs:
  node: circleci/node@5.1
  gcp-gcr: circleci/gcp-gcr@0.15.3
  cloudrun: circleci/gcp-cloud-run@1.0.2

workflows:
  build_gcloud_deploy:
    jobs:
      - tests
      - build_and_deploy_gke:
          requires:
            - tests

jobs:
  tests:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: yarn test:unit
          name: Run tests
      
  build_and_deploy_gke:
    description: Deploy using cloud run
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - cloudrun/init
      - run:
      - cloudrun/build:
          tag: gcr.io/$GOOGLE_PROJECT_ID/vue-application:$CIRCLE_SHA1
      - cloudrun/deploy:
          cluster: 'autopilot-cluster-1'
          cluster-location: us-central1
          platform: 'gke'
          image: gcr.io/$GOOGLE_PROJECT_ID/vue-application:$CIRCLE_SHA1
          service-name: 'feedback-ui-service'